---
- name: Converge
  hosts: all
  become: true
  vars:
      k3s_role: server
      k3s_cluster_init: true
      k3s_disable:
          - traefik
          - servicelb
      k3s_write_kubeconfig_mode: "0644"
  tasks:
      - name: Include k3s role
        ansible.builtin.include_role:
            name: arillso.container.k3s
