---
galaxy_info:
    author: "arillso (@arillso)"
    description: "Installs and configures Docker on Debian, RedHat, and Ubuntu."
    license: MIT
    min_ansible_version: "2.15"
    platforms:
        - name: Debian
          versions:
              - buster
              - bullseye
        - name: Ubuntu
          versions:
              - focal
        - name: EL
          versions:
              - "8"
              - "9"

    galaxy_tags:
        - docker
        - container
        - deployment
